// Auto-generated by scripts/generate-prompts.ts
// Do not edit this file manually.

import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { render } from './prompt-utils';

// It is expected that this generated file (prompts.ts) is in the same directory 
// as the .md template files it references and prompt-utils.ts.
// If not, __dirname logic might need adjustment or paths made absolute from project root.
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename); 

// --- Argument Types ---
export type SystemArgs = {
  readonly repositoryContext: string;
};


// --- Prompt Generation Functions ---

/**
 * Generates the 'system.md' prompt.
 * Template path: system.md
 */
export async function generateSystemPrompt(
  args: SystemArgs
): Promise<string> {
  const templatePath = path.resolve(__dirname, 'system.md');
  const templateContent = await fs.readFile(templatePath, 'utf-8');
  return render(templateContent, args as Record<string, string>);
}
