version: "3"

services:
  app:
    build: .
    restart: always
    env_file: .env
    environment:
    - BUN_ENV=production
    - PORT=3000
    ports:
    - "3000:3000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - repos:/app/repos
    - queue-data:/app/data
    networks:
    - reposister-network

networks:
  reposister-network:
    driver: bridge

volumes:
  repos:
  queue-data:
