version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
    - BUN_ENV=production
    - PORT=3000
    ports:
    - "3000:3000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - repos:/app/repos
    networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  repos:
